TRUNCATE TABLE threads RESTART IDENTITY CASCADE;

INSERT INTO threads (
    title, 
    description, 
    image_url, 
    category, 
    tags, 
    tier, 
    contributions, 
    active_contributions, 
    boost_expires_at, 
    member_count, 
    created_by_user_id,
    created_at,
    updated_at
) VALUES
    ('Pre-loved Apple',
    'Everything Apple. From pre-loved ipads to macbooks!',
    'https://images.unsplash.com/photo-1646621407385-528a18fbe004?q=80&w=2070&auto=format&fit=crop',
    'apple-devices',
    ARRAY['apple','iphone','macbook','trending'],
    3,
    4200,
    12,
    NOW() + INTERVAL '60 days',
    8420,
    1,
    NOW(),
    NOW()),

    ('Nintendo Lovers',
    'Everything Nintendo — consoles, games, collectibles, and events.',
    'https://images.unsplash.com/photo-1567094764148-bb14c3e6f14c?q=80&w=2070&auto=format&fit=crop',
    'gaming',
    ARRAY['gaming','esports','console','nintendo'],
    2,
    3800,
    10,
    NOW() + INTERVAL '60 days',
    5230,
    1,
    NOW(),
    NOW()),

    ('High-End PC Building & Overclocking',
    'Discussions on custom PC builds, components, and performance tuning.',
    'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=1200&auto=format&fit=crop&q=60',
    'pc-building',
    ARRAY['pc-building', 'gaming', 'overclocking', 'hardware'],
    1,
    5500,
    15,
    NOW() + INTERVAL '60 days',
    2038,
    1,
    NOW(),
    NOW()),

    ('Pre-loved Luxurious Brands',
    'Shoes, bags, jewelry, watches and premium accessories.',
    'https://images.unsplash.com/photo-1629439612315-b69e9236c8e1?w=1200&auto=format&fit=crop&q=60',
    'fashion',
    ARRAY['fashion','accessories','style','luxury'],
    1,
    1850,
    8,
    NOW() + INTERVAL '60 days',
    3420,
    1,
    NOW(),
    NOW()),

    ('IKEA Pre-Loved',
    'Furniture, decor, appliances and home improvement swap from IKEA.',
    'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=958&auto=format&fit=crop',
    'furniture',
    ARRAY['furniture','home','decor','ikea'],
    0,
    2100,
    7,
    NOW() + INTERVAL '60 days',
    2890,
    1,
    NOW(),
    NOW()),

    ('Asian Literature',
    'Swaps and discussions on classic and modern Asian books.',
    'https://images.unsplash.com/photo-1531988042231-d39a9cc12a9a?q=80&w=1170&auto=format&fit=crop',
    'books',
    ARRAY['books','media','education','asia'],
    0,
    920,
    4,
    NOW() + INTERVAL '60 days',
    1560,
    1,
    NOW(),
    NOW()),

    ('GymBros Exchange',
    'Exercise equipment, sportswear, outdoor gear and wellness products.',
    'https://images.unsplash.com/photo-1591311630200-ffa9120a540f?q=80&w=1110&auto=format&fit=crop',
    'sport',
    ARRAY['sports','fitness','wellness','gym'],
    1,
    1650,
    5,
    NOW() + INTERVAL '60 days',
    4210,
    1,
    NOW(),
    NOW()),

    ('AI Tools & Software Development',
    'Discussing the latest in machine learning, generative AI, and coding frameworks.',
    'https://images.unsplash.com/photo-1712002641088-9d76f9080889?w=1200&auto=format&fit=crop&q=60',
    'ai-tools',
    ARRAY['ai','software','coding','trending'],
    3,
    4200,
    15,
    NOW() + INTERVAL '60 days',
    2154,
    1,
    NOW(),
    NOW()),

    ('Collectible Sneakers & Streetwear Drops',
    'Talk about new releases, resale market, and styling advice for sneakers.',
    'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1200&auto=format&fit=crop&q=60',
    'fashion',
    ARRAY['fashion','sneakers','streetwear','drops'],
    2,
    3800,
    10,
    NOW() + INTERVAL '60 days',
    1928,
    1,
    NOW(),
    NOW()),

    ('MMORPGs & Online Multiplayer Games',
    'Guides, discussions, and news for MMOs and co-op titles.',
    'https://images.unsplash.com/photo-1616588589676-62b3bd4ff6d2?q=80&w=1032&auto=format&fit=crop',
    'gaming',
    ARRAY['gaming','mmorpg','online','multiplayer'],
    1,
    1850,
    6,
    NOW() + INTERVAL '60 days',
    1020,
    1,
    NOW(),
    NOW()),

    ('Vintage & Mid-Century Modern Furniture',
    'Collecting, restoring, and finding vintage and retro home decor.',
    'https://images.unsplash.com/photo-1715249891485-4b8e66b584dc?w=1200&auto=format&fit=crop&q=60',
    'furniture',
    ARRAY['furniture','vintage','decor','design'],
    2,
    2100,
    9,
    NOW() + INTERVAL '60 days',
    1200,
    1,
    NOW(),
    NOW()),

    ('Self-Help & Productivity Items',
    'Discussing strategies for personal growth, habit building, and daily output.',
    'https://images.unsplash.com/photo-1598301257942-e6bde1d2149b?w=1200&auto=format&fit=crop&q=60',
    'books',
    ARRAY['books','self-help','productivity','wellness'],
    0,
    920,
    3,
    NOW() + INTERVAL '60 days',
    2010,
    1,
    NOW(),
    NOW()),

    ('Running & Marathon Equipments',
    'Tips, gear reviews, and motivation for all levels of runners.',
    'https://images.unsplash.com/photo-1597892657493-6847b9640bac?w=1200&auto=format&fit=crop&q=60',
    'sport',
    ARRAY['sports','running','marathon','fitness'],
    1,
    1650,
    6,
    NOW() + INTERVAL '60 days',
    1029,
    1,
    NOW(),
    NOW()),

    ('DIY & Home Renovation Thread',
    'Share your DIY creations and renovation projects.',
    'https://images.unsplash.com/photo-1603227809135-512eb5c03f43?w=1200&auto=format&fit=crop&q=60',
    'furniture',
    ARRAY['diy','home','tools','renovation'],
    0,
    1900,
    5,
    NOW() + INTERVAL '60 days',
    4038,
    1,
    NOW(),
    NOW()),

    ('Sustainable & Ethical Facial Brands',
    'Discover and support sustainable skincare and beauty brands.',
    'https://images.unsplash.com/photo-1634217620030-403525c4b9de?w=1200&auto=format&fit=crop&q=60',
    'fashion',
    ARRAY['fashion','sustainability','eco-friendly','beauty'],
    1,
    1100,
    4,
    NOW() + INTERVAL '60 days',
    8420,
    1,
    NOW(),
    NOW()),

    ('Outdoor Adventures & Hiking Gear',
    'Reviews and recommendations for tents, packs, boots, and trails.',
    'https://plus.unsplash.com/premium_photo-1663127114654-37b84c0ed3ed?q=80&w=1150&auto=format&fit=crop',
    'sport',
    ARRAY['sports','outdoor','travel','gear'],
    2,
    3200,
    8,
    NOW() + INTERVAL '60 days',
    727,
    1,
    NOW(),
    NOW()),

    ('Fantasy Book Club: High Fantasy',
    'Discussing the greatest in epic fantasy novels and book series.',
    'https://images.unsplash.com/photo-1540650659171-c24a35e9cd54?q=80&w=688&auto=format&fit=crop',
    'books',
    ARRAY['books','fantasy','literature','fiction'],
    0,
    1550,
    4,
    NOW() + INTERVAL '60 days',
    8420,
    1,
    NOW(),
    NOW()),

    ('Best Smart Home Automation Hubs',
    'Comparing Google Home, Alexa, HomeKit, and custom setups.',
    'https://plus.unsplash.com/premium_photo-1758492123932-31c78cdbabe2?q=80&w=772&auto=format&fit=crop',
    'smart-home',
    ARRAY['smart-home','automation','iot','homekit'],
    2,
    4000,
    10,
    NOW() + INTERVAL '60 days',
    840,
    1,
    NOW(),
    NOW()),

    ('Creative Coding & Indie Game Devs',
    'A space for indie developers, creative coders, and hobby projects.',
    'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1200&auto=format&fit=crop',
    'ai-tools',
    ARRAY['coding','indie','gamedev','software'],
    3,
    4600,
    14,
    NOW() + INTERVAL '60 days',
    1142,
    1,
    NOW(),
    NOW()),

    ('Eco-Friendly Home Essentials',
    'Share and discover sustainable household swaps and products.',
    'https://images.unsplash.com/photo-1606813902911-cb0c5a9c3cc9?q=80&w=1200&auto=format&fit=crop',
    'furniture',
    ARRAY['eco','furniture','home','sustainability'],
    1,
    1900,
    5,
    NOW() + INTERVAL '60 days',
    1562,
    1,
    NOW(),
    NOW());

-- Make sure timestamps are set for any null values
UPDATE threads 
SET 
    created_at = NOW(),
    updated_at = NOW()
WHERE created_at IS NULL;
